### ISSUE TITLE
Install fails on node v8.9.1

### ISSUE THREAD

**Issue by Tanneguy** [panosoft/elm-grove#16]
I have a build failure on 
- node v8.9.1
- npm v5.3.0

The error is on nodegit.

As the current version of node (as per `apt-get install nodejs ` on Ubuntu) is v8.9.1, I decided to make it an independant issue rather than a comment on issue #1

**Comment by Tanneguy** [comment]
Log tail for the issue : (on ubuntu 16.04)

```
2561 info lifecycle node-pre-gyp@0.6.38~install: node-pre-gyp@0.6.38
2562 silly install nodegit@0.20.2
2563 info lifecycle nodegit@0.20.2~install: nodegit@0.20.2
2564 verbose lifecycle nodegit@0.20.2~install: unsafe-perm in lifecycle false
2565 verbose lifecycle nodegit@0.20.2~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/tann/Apps/elm-grove/node_modules/n
odegit/node_modules/.bin:/home/tann/Apps/elm-grove/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/
bin
2566 verbose lifecycle nodegit@0.20.2~install: CWD: /home/tann/Apps/elm-grove/node_modules/nodegit
2567 silly lifecycle nodegit@0.20.2~install: Args: [ '-c',
2567 silly lifecycle   'node lifecycleScripts/preinstall && node lifecycleScripts/install' ]
2568 silly lifecycle nodegit@0.20.2~install: Returned: code: 1  signal: null
2569 info lifecycle nodegit@0.20.2~install: Failed to exec install script
2570 verbose unlock done using /home/tann/.npm/_locks/staging-c9f644c27f76b5b0.lock for /home/tann/Apps/elm-grove/node_modules/.staging
2571 warn @panosoft/elm-grove@1.2.2 No repository field.
2572 verbose stack Error: nodegit@0.20.2 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
2572 verbose stack Exit status 1
2572 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
2572 verbose stack     at emitTwo (events.js:126:13)
2572 verbose stack     at EventEmitter.emit (events.js:214:7)
2572 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
2572 verbose stack     at emitTwo (events.js:126:13)
2572 verbose stack     at ChildProcess.emit (events.js:214:7)
2572 verbose stack     at maybeClose (internal/child_process.js:925:16)
2572 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2573 verbose pkgid nodegit@0.20.2
2574 verbose cwd /home/tann/Apps/elm-grove/node_modules
2575 verbose Linux 4.4.0-97-generic
2576 verbose argv "/usr/bin/node" "/usr/bin/npm" "link"
2577 verbose node v8.9.1
2578 verbose npm  v5.3.0
2579 error code ELIFECYCLE
2580 error errno 1
2581 error nodegit@0.20.2 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
2581 error Exit status 1
2582 error Failed at the nodegit@0.20.2 install script.
2582 error This is probably not a problem with npm. There is likely additional logging output above.
2583 verbose exit [ 1, true ]
```

**Comment by Tanneguy** [comment]
Closed by misclicking I guess

**Comment by cscalfani** [comment]
What version of Ubuntu are you using?

**Comment by cscalfani** [comment]
As a test, I ran Ubuntu 16.04.3 LTS in a Docker container.

I needed to run the following command to get past this error: `apt install libssl-dev`according to this [nodegit issue](https://github.com/nodegit/nodegit/issues/1134#issuecomment-253972367)

But then I got a different error (which you may not get since you're probably not running a minimal version of Ubuntu):

`no acceptable C compiler found in $PATH`

This was fixed by running the following command: `apt-get install build-essential` according to this [StackOverflow response](https://stackoverflow.com/a/19816655).

Now grove works on Ubuntu 16.04 with node 8.9.1 and npm 5.3.0.

**Comment by Tanneguy** [comment]
Ok fixed as per the above comment, closing issue.
